env:
  commonjs: true
  es6: true
  node: true
extends:
  - standard
parserOptions:
  ecmaVersion: 2018
rules: 
  quotes:
    - error
    - double
  semi: 
    - error
    - always
  space-before-function-paren:
    - error
    - anonymous: never
      asyncArrow: always
      named: never
